### ISSUE TITLE
*Any* way to fix an erroneous CDN link?

### ISSUE THREAD

**Issue by lgolding** [rgrove/rawgit#100]
I tested out rawgit by pasting the github URL of my document into the top box -- but I accidentally pasted the production link into my browser, rather than the dev link. I understand this means that the CDN is caching my document "permanantly". Is there no way to remove it?

Thanks,
Larry

**Comment by rgrove** [comment]
Why do you need to remove it?

**Comment by lgolding** [comment]
The [link](https://cdn.rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20(SARIF).html) points to a specification we are developing, which is still undergoing revision. What I want is to put a link to the work-in-progress on rawgit (which I have [done](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20(SARIF).html)), but when the spec is finalized, I want to make a copy of it ("SARIF_v1.html", for example), and link to _that_ from the CDN. But I accidentally linked the work-in-progress from the CDN. Does that make sense?

**Comment by lgolding** [comment]
Oh. I guess I answered my own question. There's no harm in leaving the old one if I add a new one with a different name.

**Comment by rgrove** [comment]
Yep, exactly. Or, if you don't want to change the filename, you can tag the current commit with `git tag <tag name>`, push the tag to your repo with `git push --tags`, and then use the tag name instead of the branch name ("master") in the RawGit URL. That way, RawGit will pull from the tagged commit, and if you need to push changes, you can just push a new tag and change the URL to point to that tag, and so on.

Hope that helps!

**Comment by lgolding** [comment]
Perfectly clear, thanks.
