### ISSUE TITLE
Content-Length header on CDN

### ISSUE THREAD

**Issue by Anthchirp** [rgrove/rawgit#106]
Can we get a content-length header on https://cdn.rawgit.com urls?
raw.githubusercontent.com does supply these

**Comment by rgrove** [comment]
RawGit uses chunked encoding so that we can begin streaming responses to the client instantly as soon as we start getting bytes from GitHub. Using the `Content-Length` header would require us to buffer the entire response from GitHub before we could start sending bytes to the client, which would result in slower responses and increased memory pressure on RawGit. So, unfortunately, the answer is no. But thanks for asking!

I went into more technical detail in this earlier issue, if you're interested: https://github.com/rgrove/rawgit/issues/81

**Comment by Anthchirp** [comment]
Thank you for the explanation - and for rawgit of course :)

**Comment by neurospeech** [comment]
You can use `Content-Length` if github sends it, for raw.githubusercontent.com does return valid `Content-Length`, all you need to do is just pass it on.

**Comment by rgrove** [comment]
@neurospeech Please read [this detailed explanation](https://github.com/rgrove/rawgit/issues/81#issuecomment-144792930) of why this is not possible.

RawGit is designed to stream chunked responses to the client as quickly as possible both to improve performance and to reduce memory overhead. [Chunked responses are prohibited from including `Content-Length` headers](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4), so RawGit cannot send a `Content-Length` header.
