### ISSUE TITLE
Add SRI Hash support

### ISSUE THREAD

**Issue by jamesshannon** [rgrove/rawgit#112]
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

Right now my workflow is to go to rawgit, get the CDN URL, then go to https://www.srihash.org/

It'd be nice if rawgit created the hashes, and would also increase the use of SRI, which is probably a really good thing when using libraries from "unknown" third parties on github.

On second thought, I guess that using a specific commit does effectively the same thing (assuming you trust MaxCDN and Github, which I do). And you can't use an SRI hash on a /master/ file (MaxCDN seems to occasionally update it) anyways, so now that I think of it this is of limited use, but I might as well log this anyways. :)

**Comment by rgrove** [comment]
It's an interesting idea, but as you point out, using a commit-based URL achieves effectively the same level of assurance that RawGit could provide by auto-generating an SRI hash, since either way you still have to trust GitHub, RawGit, and MaxCDN. If you already trust GitHub, RawGit, and MaxCDN, then using HTTPS will ensure that a third party can't tamper with your file's contents in transit.

If you don't trust GitHub, RawGit, and/or MaxCDN, or if you simply want to guard against one of them being compromised and serving malicious content, then manually generating your own SRI hash based on a known-good file still seems like the best approach.

Thanks for the suggestion though!
