### ISSUE TITLE
Best way to handle moving repo?

### ISSUE THREAD

**Issue by leram84** [rgrove/rawgit#155]
Let me start by saying I am a TOTAL git noob. I just setup my first [repo](https://github.com/leram84/layer.Cake) which is just an HTML/CSS theme for [Organizr](https://github.com/causefx/Organizr). Since Organizr is still in dev and constantly adding new features, I have needed to update the theme after every Org update to include new sections... I THOUGHT rawgit would be the perfect solution to this since it would let anyone sync directly to my repo and they would get automatic updates when my repo was updated. Obviously i jumped the gun a little since everything was working so perfectly in dev, i missed the part about the cdn caching permanently. I'm just wondering if there is an easy fix to this that im missing?

**Comment by rgrove** [comment]
The best thing that you can do to ensure the CDN serves fresh files is to [use a tag or commit hash](https://github.com/rgrove/rawgit/blob/master/FAQ.md#how-long-does-the-cdn-cache-files-how-can-i-make-it-refresh-my-file) in the URL instead of a branch. This does mean that you'll need to update the URL you're using every time you push new changes, though.

If you need to distribute URLs that you won't be able to replace later, you can use a URL pointing to the master branch. The CDN will refresh master branch URLs every 24 hours. I don't advertise this because it may change someday and I don't want people to rely on it too much, but for now it may be enough in your case.

**Comment by leram84** [comment]
oh man... u saved my but big time!! I was afraid i was gonna have to scrap the whole thing. 24 hour updates will work PERFECTLY, and don't worry, i doubt more than 20 ppl will ever use my repo lol. THANK YOU!
