### ISSUE TITLE
Support /crossdomain.xml

### ISSUE THREAD

**Issue by ceefour** [rgrove/rawgit#161]
Required to properly host HLS files (among others?)

The following is a sane default, should be accessible as http://rawgit.com/crossdomain.xml and https://rawgit.com/crossdomain.xml (and cdn.rawgit.com)

```
<?xml version="1.0"?>
<!DOCTYPE cross-domain-policy SYSTEM
"http://www.adobe.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
  <allow-access-from domain="*" />
</cross-domain-policy>
```

**Comment by rgrove** [comment]
@ceefour What's your use case for HLS?

**Comment by ceefour** [comment]
Use case is to allow playing video file stored in GitHub repository. Usually small videos, handy for tutorial, lecture/course supplement, or project documentation.

**Comment by rgrove** [comment]
@ceefour Is there some reason you can't use GitHub Pages, YouTube, or Vimeo for this?

Streaming video is pretty far afield from RawGit's primary focus, and the RawGit CDN isn't configured in a way that would work well for streaming video. Making the CDN work well for streaming video would make it work less well for other kinds of files, so that's not really an option. But there are many free video hosting services, so this doesn't seem like something RawGit needs to do.

**Comment by ceefour** [comment]
Sure, no problem.

For my use case, YouTube cannot be used, because it is a sample on how to use Flowplayer and HLS.
