### ISSUE TITLE
Optimize Cache-Control headers

### ISSUE THREAD

**Issue by mattbrundage** [rgrove/rawgit#177]
The FAQ states that "_The CDN caches files permanently based on their path._"

Based on this info, may I recommend setting a [far-future cache-control header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) of 1 year. Currently, the max-age of assets served from cdn.rawgit.com is `86400` (24 hours), which is very low.

Also, consider the "Cache-Control: immutable" directive. In browsers that support it, it saves the client from having to perform revalidation.

**Comment by rgrove** [comment]
Hi Matt. You're apparently looking at a CDN URL that's using the `master` branch. RawGit only caches `master` branch URLs for 24 hours and doesn't mark them as immutable, because the contents of the `master` branch are likely to change and too many people were using `master` branch CDN URLs and then asking why the CDN never picked up their changes.

The same [FAQ answer](https://github.com/rgrove/rawgit/blob/master/FAQ.md#how-long-does-the-cdn-cache-files-how-can-i-make-it-refresh-my-file) you're referring to also advises using a tag or commit ref rather than a branch in the URL. If you do this, you'll see that the CDN does serve a far-future cache-control header with the `immutable` directive.

**Comment by mattbrundage** [comment]
Good deal. Thanks.
