### ISSUE TITLE
Handling branches other than master?

### ISSUE THREAD

**Issue by greggman** [rgrove/rawgit#184]
Pasting in 

    https://github.com/mrdoob/three.js/blob/dev/examples/js/utils/SceneUtils.js

produces

    https://cdn.rawgit.com/mrdoob/three.js/dev/examples/js/utils/SceneUtils.js

where as pasting in

    https://github.com/mrdoob/three.js/blob/master/examples/js/utils/SceneUtils.js

produces

    https://cdn.rawgit.com/mrdoob/three.js/0949e59f/examples/js/utils/SceneUtils.js

Is that intentional? Someone referring to the top one above is going to end up with a broken page as the code changes.  Maybe an error like "error: not master branch" would be better if a permanent link is not going to be generated?

**Comment by rgrove** [comment]
Some people want to use branches in their URLs. It's also not always possible for RawGit to determine what's a branch, what's a tag, and what's a commit hash. `deadbeef` could be all three.

`master` is converted to a commit ref for CDN URLs because too many people were generating master branch CDN URLs and then begging me to purge the cache when they discovered the CDN caches things for a long time.
