### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by fattoh** [rgrove/rawgit#201]
I use windows 10 and after all steps of installation, I have these errors in the
>npm start 

C:\Windows\System32\rawgit>npm start

> rawgit@0.0.1 start C:\Windows\System32\rawgit
> NODE_ENV=development nodemon

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rawgit@0.0.1 start: `NODE_ENV=development nodemon`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rawgit@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fattoh\AppData\Roaming\npm-cache\_logs\2020-03-05T14_44_19_638Z-debug.log

**Comment by rgrove** [comment]
Sorry, RawGit was written to run on Linux and macOS. Getting it running on Windows is probably possible, but would take some work. Since the project is no longer under active development I'm going to close this issue, but please feel free to fork RawGit and improve its Windows compatibility if that's something you're interested in.
