### ISSUE TITLE
Any way to update the cached content in cdn.rawgit.com ?

### ISSUE THREAD

**Issue by luochen1990** [rgrove/rawgit#55]
Thx for your great job.  I really want to use cdn.rawgit.com which is faster than rawgit.com and saves money for you. but it prevent me to use cdn.rawgit.com that there is no way to flash the old content.

so, is there any way to do this?

Will it be a solution that when rawgit.com/a/b/c is visited, cdn.rawgit.com/a/b/c will be updated ?

**Comment by rgrove** [comment]
No, sorry. Please see http://rawgit.com/faq#cdn-ttl.

**Comment by Jmuccigr** [comment]
I think I misunderstood your instructions there. In order to use tags, it's necessary to create a new tag and change my URL to include that new tag. IOW, even the versions with tags in the URL get cached.

**Comment by rgrove** [comment]
Yep, every CDN URL will always get cached (because that's what a CDN does). The point of using tag- or commit-based URLs is that a those URLs can only ever point to one version of a file, so it's fine for them to get cached permanently. When you need to point to a newer version of the file, you change the URL to the new tag or commit.

Branch URLs aren't ideal for the CDN since the version of a file that's on a branch can change, but the CDN will permanently cache the first version it sees with that URL.
