### ISSUE TITLE
add bookmarklet

### ISSUE THREAD

**Issue by dvdrtrgn** [rgrove/rawgit#61]
I didn't see an offering for a quick dev link peek. I'm using this...
:bookmark:  `javascript:(function(L){L.href=L.href.replace('raw.githubusercontent','rawgit')}(location));`

**Comment by rgrove** [comment]
Thanks for sharing!

There's also a [Chrome extension](https://chrome.google.com/webstore/detail/rawgit-for-github/mobohgekahaknpfhiknjgepliebadkko) now.

I'm going to close this issue because I don't have plans to build bookmarklets / extensions / etc. myself, but please feel free to comment with links to third party projects.
