### ISSUE TITLE
Empty response seems cached

### ISSUE THREAD

**Issue by kernicPanel** [rgrove/rawgit#64]
https://cdn.rawgit.com/rstacruz/flatdoc/v0.9.0/flatdoc.js returns nothing, but https://rawgit.com/rstacruz/flatdoc/v0.9.0/flatdoc.js is ok.

Is there a way to clear cdn cache ?
Or maybe you could disable cache for empty files ?

@rgrove : If you don't have time to handle this, I'll try to make a pull request asap.

**Comment by rgrove** [comment]
Strange. It looks like the CDN had different versions of the file on different edge nodes; most were complete, but a few were empty, so blank files were being served to people in geographic areas near the bad edge nodes. In theory the CDN is supposed to ensure that a file is only requested from RawGit once and then all edge nodes cache the same content, but it looks like something glitched and some of the nodes got bad data.

I've flushed the file out of the cache and the nodes should repopulate with the correct response now. Sorry about that!

Hopefully this won't happen again, but if it does, a temporary workaround would be to request the file by its commit ref instead of the tag (or vice versa, depending on which URL is poisoned in the cache).
