### ISSUE TITLE
GitHub Releases

### ISSUE THREAD

**Issue by cbas** [rgrove/rawgit#70]
I am getting 404 from Rawgit CDN when requesting files on GitHub Releases. This was working a few weeks ago, I vaguely remember. The rawgit.com website also still greenlights the input address.

E.g.
200 https://github.com/migme/beachball/releases/download/v2.2.0/migme-beachball.min.js
404 https://rawgit.com/migme/beachball/releases/download/v2.2.0/migme-beachball.min.js
404 https://cdn.rawgit.com/migme/beachball/releases/download/v2.2.0/migme-beachball.min.js

Any ideas what went wrong?

PS: Seems to be related to #66

**Comment by rgrove** [comment]
I'm not sure what you were seeing a few weeks ago, but RawGit has never proxied requests for release files. #66 is just a feature request that I haven't implemented yet.

The fact that rawgit.com thinks a release URL is something it can handle is definitely a bug though; thanks for pointing that out. It's happening because release URLs appear to follow the `/user/repo/branch/path` format RawGit is looking for, even though GitHub treats them differently from repo URLs. I've filed #71 to track that.

**Comment by cbas** [comment]
Oh my apologies. My memory may be confused by the behaviour of #71. :confused:

Would you consider proxying release files?

**Comment by rgrove** [comment]
Yep, I'll probably implement release proxying for the CDN. Just haven't had time yet.

**Comment by davedoesdev** [comment]
This works for me: https://github.com/davedoesdev/rawgit-openshift/commit/80aad34d084f300127d70fe73ba695cd163138fb
