### ISSUE TITLE
Ability to concatenate multiple files

### ISSUE THREAD

**Issue by abishekrsrikaanth** [rgrove/rawgit#84]
Is it possible to support concatenating multiple libraries?

```
https://cdn.rawgit.com/adobe-webplatform/Snap.svg/master/dist/snap.svg-min.js+vuejs/vue/dev/dist/vue.min.js
```

The above url should concatenate both the libraries on a single request. This way we can concatenate multiple libraries on a single request.

**Comment by rgrove** [comment]
This is not currently possible, but I'll consider this a feature request. Thanks!

**Comment by neoascetic** [comment]
Why do you need this for development purposes? What is next? JS
minification? Images optimization?

**Comment by rgrove** [comment]
@neoascetic The RawGit CDN is suitable for production use, and file concatenation is a feature that several JS-oriented CDNs offer.

Relying on SPDY (or HTTP2, which RawGit's CDN doesn't yet support but hopefully will someday soon) may be a better option, but concatenation can still be useful for clients that don't support SPDY/HTTP2.

**Comment by neoascetic** [comment]
> file concatenation is a feature that several JS-oriented CDNs offer

Wow, didn't know this.

**Comment by rgrove** [comment]
Yeah. [Yahoo's YUI CDN](http://yuiblog.com/blog/2008/07/16/combohandler/) was one of the first to support this. [jsdelivr](https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request) also supports it, but I don't think cdnjs does.

The more I think about this, though, the more I think SPDY/HTTP2 are probably the way forward, since they don't require any special considerations on the CDN side, and they provide the efficiency benefits of concatenation without the drawback of invalidating the entire cached concatenated response when only one file changes.

RawGit already supports SPDY, and it looks like [most modern browsers support HTTP2 now](http://caniuse.com/#feat=http2), so I think I'll go ahead and close this request, and plan to offer HTTP2 support as soon as MaxCDN support it, which appears to be planned for [later this year](https://www.maxcdn.com/blog/cdn-http2/).
