### ISSUE TITLE
Keeps redirecting to github

### ISSUE THREAD

**Issue by idibidiart** [rgrove/rawgit#87]
I want to serve this over rawgit

https://rawgit.com/idibidiart/ssl/master/apple-app-site-association

And it keeps getting redirected to 

https://raw.githubusercontent.com/idibidiart/ssl/master/apple-app-site-association

Not very useful is it?

**Comment by rgrove** [comment]
Without a file extension, RawGit has no way of knowing what MIME type it should use to serve the file. Since RawGit's only purpose is to serve files from GitHub with MIME types that GitHub won't serve itself, there's no reason for RawGit to serve this file, so it redirects you to GitHub where you'll get the same bytes without costing me any money.

So, in that sense, yeah, I think it's pretty useful!

**Comment by idibidiart** [comment]
Apple requires no extension on that file. So i guess i have to find another way to prototype.

maybe  you can infer from  parent folder name if no extension is present? I can make that as "json" 

I like how you just shutdown the conversation without any back and forth. Maybr  i fork it and do that? Or are you open to this as enhancement ?

**Comment by rgrove** [comment]
> I like how you just shutdown the conversation without any back and forth.

I answered your snarky question with a snarky explanation of how this is RawGit working as it was designed to work. Then I closed the issue because there was nothing more for me to do here. In this repo, I treat open issues as things I need to do or think about. In your repos, you can leave issues open as long as you want.

> Maybr i fork it and do that? Or are you open to this as enhancement ?

Please feel free to fork if you like, but I'm not interested in changing this behavior in RawGit. Thanks!
