### ISSUE TITLE
MaxCDN doesn't cache? Browser-side?

### ISSUE THREAD

**Issue by u8y7541** [rgrove/rawgit#91]
rawgit.com says that the content is permanently cached. I tried to access my repo through rawgit's MaxCDN and it worked. When I updated the repo and tried again, the MaxCDN link also updated. Is this browser caching (I have a JS project) or is it MaxCDN?

**Comment by rgrove** [comment]
"Indefinitely" might be a more accurate word than "permanently". Once a file is cached by a CDN node, that node will serve that file from the cache unless it is purged from the cache. Files served from the CDN are also served with far-future expiration headers so that browsers will cache them indefinitely as well.

That said, there are a number of reasons why a subsequent request to the CDN for the same URL might return updated content. Technically, MaxCDN doesn't cache a URL until the second time it's requested (to avoid caching URLs that only get requested once and never again). It's also possible that a request could get routed to a different CDN node that doesn't yet have the file in its cache. And, while it happens very rarely (only twice so far), I do sometimes need to purge the CDN cache to fix a bug or something.

So, a file isn't _guaranteed_ to be cached permanently by the CDN, but you should _assume_ that it will be rather than hoping the CDN will pick up changes. Hope this helps!

**Comment by u8y7541** [comment]
Well... this is weird. It happened again. Twice. What's going on? Is it my browser cache or is it a huge coincidence?

**Comment by rgrove** [comment]
What URLs is this happening with?

**Comment by u8y7541** [comment]
Here it is: cdn.rawgit.com/u8y7541/canvas-game/master/index.html
Wow, it isn't happening anymore for some reason. Weird.

**Comment by rgrove** [comment]
Yeah, everything seems fine here.

In any case, if you want to ensure that your CDN URLs always reflect a specific version of your code, you can use a tag name or commit ref in the URL instead of a branch.

**Comment by u8y7541** [comment]
Yep, ditching this in favor of hosting my JS on a gh-pages branch, so I can just rebase master and live update.
