### ISSUE TITLE
Add short usage example to README.md

### ISSUE THREAD

**Issue by bgilmer77** [rgrove/rawgit#95]
It might be helpful to add the following very short example to the README.md file:

"To check your installation, point a local web browser to a github file using the following syntax:
localhost:5000/user/repo/branch/file.  
For example, localhost:5000/rgrove/rawgit/master/file_to_render.html"

**Comment by rgrove** [comment]
Good idea! If you open a PR for this, I'll merge it.

**Comment by bgilmer77** [comment]
Thanks - I have a contribution ready but am getting permission errors when I try to push it.  I am still getting the hang of github so I might be doing something wrong, but I wonder if I have to be a member of the project in order to be able to push?

**Comment by rgrove** [comment]
No worries! For a small change like editing the readme, you can actually browse right to the file and edit it on GitHub, and GitHub will guide you through the process of opening a pull request.

Just go to https://github.com/rgrove/rawgit/blob/master/README.md and then click the pencil icon (to the right of the "History" button) to open the editor. Once you've made the changes, scroll to the bottom of the page and type a commit message like "Add usage example to README. Fixes #95", then click "Commit Changes".

If you were making more complicated changes, then instead of using the online editor you'd fork the RawGit repo, then clone your fork (not the original repo), make your changes locally, commit them, push them back to your fork, and then browse to your fork on GitHub to open a PR. In this case, it sounds like you were trying to push your changes back to the RawGit repo instead of your own fork, which GitHub doesn't allow because you don't have commit access to this repo.

Hope this helps, and thanks for the contribution!

**Comment by bgilmer77** [comment]
I decided to take the longer path so I could become more familiar with github.  I forked the project to my workspace, made the change, and generated a pull request.  It looks good as far as I can tell, but please let me know if there is something I should have done differently.

As a *NIX admin, there is not too much I can contribute from a code perspective, but I can help with documenting setup/installation.

Thanks for the great utility!

**Comment by rgrove** [comment]
Thanks for the contribution!
